version: 2.1

orbs:
  gcp-gke: circleci/gcp-gke@0.2.0
  gcr: circleci/gcp-gcr@0.8

jobs:
  build:
    description: Build static app image using gcp orb
    machine: true
    steps:
      - checkout
      - gcr/build-image:
          image: eightbitguy-${CIRCLE_BRANCH}-$(echo $CIRCLE_SHA1 | cut -c -7)


  push:
    description: Push docker image to google container registry
    machine: true
    steps:
      - gcr/gcr-auth
      - gcr/push-image:
          image: eightbitguy-${CIRCLE_BRANCH}-$(echo $CIRCLE_SHA1 | cut -c -7)


  deploy:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    steps:
      - gcp-gke/install
      - gcp-gke/init
      - gcp-gke/rollout-image:
          cluster: eightbitguy-website-cluster-1
          container: ui-app
          deployment: eightbitguy.in
          image: gcr.io/eightbitguy-website/eightbitguy-master-bfc38cc
#
workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build
      - push:
          requires:
            - build
      - deploy
          requires:
            - push
