version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t us.gcr.io/eightbitguy-website/eightbitguy-website-${CIRCLE_BRANCH}-${CIRCLE_SHA1} .
      - run: docker push us.gcr.io/eightbitguy-website/eightbitguy-website-${CIRCLE_BRANCH}-${CIRCLE_SHA1}

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
