name: staging
on:
  push:
    branches:
      - master

jobs:
  build-test-deploy:
    name: Build, Test & Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    env:
      EMAIL_SERVICE_ID: ${{ secrets.EMAIL_SERVICE_ID }}
      EMAIL_TEMPLATE_ID: ${{ secrets.EMAIL_TEMPLATE_ID }}
      EMAIL_USER_ID: ${{ secrets.EMAIL_USER_ID }}
    steps:
      - name: Check-out repo..
        uses: actions/checkout@v2

      - name: Using node.js ${{ matrix.node-version }}..
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing dependencies..
        run: npm install

      - name: Inject env variables in to the build..
        run: echo REACT_APP_EMAIL_SERVICE_ID=${{ secrets.EMAIL_SERVICE_ID }} >> .env
      - name: Inject env variables in to the build..
        run: REACT_APP_EMAIL_TEMPLATE_ID=${{ secrets.EMAIL_TEMPLATE_ID }} >> .env
      - name: Inject env variables in to the build..
        run: REACT_APP_EMAIL_USER_ID=${{ secrets.EMAIL_USER_ID }}" >> .env >> .env

      - name: build
        run: npm run build:all

      - name: Injecting AWS creds..
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploying
        run: aws s3 sync build/ s3://${{secrets.PRODUCTION_BUCKET_NAME}} --acl public-read

      - name: Invalidate
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.PRODUCTION_DISTRIBUTION }}
          PATHS: '/*'
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}g
